name = "r2chiselimages"
main = "src/index.ts"
compatibility_date = "2022-06-29"
account_id = "70307c193122a50d5b62eed4a0b7cb84"
tsconfig = "./tsconfig.json"

workers_dev = false
route = "https://r2.weirdgloop.org/*"

r2_buckets  = [
  { binding = "CHISEL_IMAGES", bucket_name = "chisel-images", preview_bucket_name =  "" },
  { binding = "IMGUR_BACKUP", bucket_name = "imgur-backup", preview_bucket_name =  "" }
]